"""服务端业务模块。"""

from __future__ import annotations

ACTIVE_SESSION_INDEX = "uq_sessions_single_active"

CREATE_ACTIVE_SESSION_INDEX = (
    f"CREATE UNIQUE INDEX IF NOT EXISTS {ACTIVE_SESSION_INDEX} "
    "ON sessions (tenant_id, user_id) WHERE status != 'ENDED'"
)

DROP_ACTIVE_SESSION_INDEX = f"DROP INDEX IF EXISTS {ACTIVE_SESSION_INDEX}"

ACTIVE_FAMILY_MEMBER_INDEX = "uq_family_members_single_active"

CREATE_ACTIVE_FAMILY_MEMBER_INDEX = (
    f"CREATE UNIQUE INDEX IF NOT EXISTS {ACTIVE_FAMILY_MEMBER_INDEX} "
    "ON family_members (tenant_id, user_id) WHERE status = 'ACTIVE'"
)

DROP_ACTIVE_FAMILY_MEMBER_INDEX = f"DROP INDEX IF EXISTS {ACTIVE_FAMILY_MEMBER_INDEX}"
